FROM fusuf/whatsasena:latest

RUN git clone https://github.com/unni-settan/AchuMwol /root/WhatsAsenaDuplicated
WORKDIR /root/WhatsAsenaDuplicated/
ENV TZ=Europe/Istanbul
RUN npm install supervisor -g
RUN yarn install --no-audit
RUN git clone https://github.com/unni-settan/media

CMD ["node", "bot.js"]
